#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/usr/bin/eww -c $HOME/.config/eww/dashboard"
cmd="xdg-open"

if [[ "$1" == "--firefox" ]]; then
	eww -c ~/.config/eww/dashboard kill && firefox &

elif [[ "$1" == "--telegram" ]]; then
	eww -c ~/.config/eww/dashboard kill && $cmd "https://web.whatsapp.com" &

elif [[ "$1" == "--github" ]]; then
	eww -c ~/.config/eww/dashboard kill &&  $cmd "https://github.com" &

elif [[ "$1" == "--reddit" ]]; then
	eww -c ~/.config/eww/dashboard kill &&  $cmd "https://reddit.com" &

elif [[ "$1" == "--code" ]]; then
	eww -c ~/.config/eww/dashboard kill && code &

elif [[ "$1" == "--discord" ]]; then
	eww -c ~/.config/eww/dashboard kill && discord &

elif [[ "$1" == "--spotify" ]]; then
	eww -c ~/.config/eww/dashboard kill && tidal-hifi &
fi
