#!/bin/sh

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

#if the theme is not dark then we need to switch to it
if [ $THEMEIS != "dark.css" ]; then
    SWITCHTO="-dark"
fi

#set the waybar theme
ln -sf ~/.config/waybar/style/style$SWITCHTO.css ~/.config/waybar/style.css

#set the kitty theme
ln -sf ~/.config/kitty/themes/theme$SWITCHTO.conf ~/.config/kitty/theme.conf

#set the kitty conf
ln -sf ~/.config/kitty/conf/kitty$SWITCHTO.conf ~/.config/kitty/kitty.conf


#set the rofi theme
ln -sf ~/.config/rofi/launchers/type-6/launcher$SWITCHTO.sh ~/.config/rofi/launcher.sh

#set the xfce theme
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
if [ $THEMEIS != "dark.css" ]; then
    xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark"
else
 xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Light"
fi

xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus$SWITCHTO"

#set the GTK theme
gsettings set org.gnome.desktop.interface icon-theme "Adwaita$SWITCHTO"

if [ $THEMEIS != "dark.css" ]; then
    gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
else
gsettings set org.gnome.desktop.interface icon-theme "Papirus-Light"
fi

#change the background image and be cool about it ;)
swww img ~/.config/hypr/wallpaper$SWITCHTO.jpg --transition-fps 60 --transition-type wipe --transition-duration 2

#update the sddm image
ln -sf /usr/share/sddm/themes/sdt/Backgrounds/wallpaper$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg

#restart the waybar
killall -SIGUSR2 waybar
